package com.group.apomsproject;


import java.io.BufferedWriter;
import java.io.FileWriter;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class DeleteItemGUI extends javax.swing.JFrame {
    private final FileOperations fileOps = new FileOperations();
    private final String className = "Item"; 

    /**
     * Creates new form DeleteItemGUI
     */
    public DeleteItemGUI() {
        initComponents();
        
        tblDeleteItem.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {},
        new String [] {
            "Item ID", "Item Name", "Supplier ID", "Stock Level", "Unit Price", "Reorder Level"}
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSearchKeyword = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDeleteItem = new javax.swing.JTable();
        comboSearchBy = new javax.swing.JComboBox<>();

        jLabel2.setText("Item ID:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Delete Item");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        tblDeleteItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Item ID", "Item Name", "Supplier ID", "Stock Level", "Unit Price", "Reorder Level"
            }
        ));
        jScrollPane1.setViewportView(tblDeleteItem);

        comboSearchBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item ID", "Item Name", "Supplier ID", "Supplier Name" }));
        comboSearchBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSearchByActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(comboSearchBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSearchKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(87, 87, 87)))
                                .addComponent(btnSearch)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(comboSearchBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDelete)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String searchBy = comboSearchBy.getSelectedItem().toString().trim();  // ComboBox selection
        String keyword = txtSearchKeyword.getText().trim();                   // User input

        if (keyword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a search keyword.");
            return;
        }

        // Map ComboBox label to CSV header key
        Map<String, String> attributeMap = new HashMap<>();
        attributeMap.put("Item ID", "Item Code");
        attributeMap.put("Item Name", "Item Name");
        attributeMap.put("Supplier ID", "Supplier ID");
        attributeMap.put("Supplier Name", "Supplier Name");

        String csvKey = attributeMap.getOrDefault(searchBy, "");  // Get corresponding CSV column
        if (csvKey.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Invalid search attribute.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblDeleteItem.getModel();
        model.setRowCount(0); // Clear table

        List<Map<String, String>> allItems = fileOps.ReadFile(className + ".csv");
        boolean found = false;

        for (Map<String, String> row : allItems) {
            if (keyword.equalsIgnoreCase(row.get(csvKey))) {
                model.addRow(new Object[]{
                    row.get("Item Code"),
                    row.get("Item Name"),
                    row.get("Supplier ID"),
                    row.get("Stock Level"),
                    row.get("Unit Price"),
                    row.get("Reorder Level")
                });
                found = true;
                // Do not break here if multiple matches are allowed
            }
        }

        if (!found) {
            JOptionPane.showMessageDialog(this, searchBy + " not found.");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String searchBy = comboSearchBy.getSelectedItem().toString().trim();  // ComboBox selection
        String keyword = txtSearchKeyword.getText().trim();                   // User input

        if (keyword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a search keyword.");
            return;
        }

        // Map ComboBox label to CSV header key
        Map<String, String> attributeMap = new HashMap<>();
        attributeMap.put("Item ID", "Item Code");
        attributeMap.put("Item Name", "Item Name");
        attributeMap.put("Supplier ID", "Supplier ID");
        attributeMap.put("Supplier Name", "Supplier Name");

        String csvKey = attributeMap.getOrDefault(searchBy, "");
        if (csvKey.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Invalid deletion attribute.");
            return;
        }

        List<Map<String, String>> allItems = fileOps.ReadFile(className + ".csv");
        boolean deleted = false;

        Iterator<Map<String, String>> iterator = allItems.iterator();
        while (iterator.hasNext()) {
            Map<String, String> row = iterator.next();
            if (keyword.equalsIgnoreCase(row.get(csvKey))) {
                int confirm = JOptionPane.showConfirmDialog(this,
                    "Are you sure you want to delete this item?\n" + csvKey + ": " + keyword,
                    "Confirm Deletion", JOptionPane.YES_NO_OPTION);

                if (confirm == JOptionPane.YES_OPTION) {
                    iterator.remove();
                    deleted = true;
                }
                break; // Only delete the first match
            }
        }

        if (deleted) {
            try {
                // Reassign Item IDs in sequence
                for (int i = 0; i < allItems.size(); i++) {
                    String newItemID = String.format("IT%03d", i + 1); // Format: IT001, IT002, etc.
                    allItems.get(i).put("Item Code", newItemID); // Ensure the key matches your CSV header
                }

                // Write back to file
                List<String> headers = HeaderRegistry.getHeaders(Class.forName("com.group.apomsproject." + className));
                try (BufferedWriter bw = new BufferedWriter(new FileWriter(className + ".csv"))) {
                    bw.write(String.join(",", headers));
                    bw.newLine();
                    for (Map<String, String> row : allItems) {
                        StringBuilder line = new StringBuilder();
                        for (int j = 0; j < headers.size(); j++) {
                            String val = row.getOrDefault(headers.get(j), "");
                            if (val.contains(",") || val.contains("\"") || val.contains("\n")) {
                                val = "\"" + val.replace("\"", "\"\"") + "\"";
                            }
                            line.append(val);
                            if (j < headers.size() - 1) line.append(",");
                        }
                        bw.write(line.toString());
                        bw.newLine();
                    }
                }

                ((DefaultTableModel) tblDeleteItem.getModel()).setRowCount(0); // Clear table
                JOptionPane.showMessageDialog(this, "Item deleted and IDs reindexed successfully.");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error while updating entries: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, searchBy + " not found. No entry deleted.");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void comboSearchByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSearchByActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSearchByActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteItemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteItemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteItemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteItemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DeleteItemGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> comboSearchBy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDeleteItem;
    private javax.swing.JTextField txtSearchKeyword;
    // End of variables declaration//GEN-END:variables
}
