package com.group.apomsproject;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel; // <-- This is needed for JTable model

public class EditItemGUI extends javax.swing.JFrame {

    /**
     * Creates new form EditItemGUI
     */
    public EditItemGUI() {
        initComponents();
        
        String[] columns = {"Item Name", "Supplier ID", "Stock Level", "Unit Price", "Reorder Level"};
        DefaultTableModel model = new DefaultTableModel(columns, 0); // 0 rows initially
        tblItemEdit.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSearchKeyword = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItemEdit = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        comboSearchBy = new javax.swing.JComboBox<>();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Edit Item");

        txtSearchKeyword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchKeywordActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblItemEdit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblItemEdit);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        comboSearchBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item ID", "Item Name", "Supplier ID", "Supplier Name" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(164, 164, 164))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(238, 238, 238)
                                .addComponent(btnUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comboSearchBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSearchKeyword)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearch)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearchKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboSearchBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnCancel))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeywordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchKeywordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchKeywordActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String searchBy = comboSearchBy.getSelectedItem().toString().trim();  // ComboBox selection
        String keyword = txtSearchKeyword.getText().trim();                   // User input

        if (keyword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a search keyword.");
            return;
        }
        
        Map<String, String> attributeMap = new HashMap<>();
        attributeMap.put("Item ID", "Item Code");
        attributeMap.put("Item Name", "Item Name");
        attributeMap.put("Supplier ID", "Supplier ID");
        attributeMap.put("Supplier Name", "Supplier Name");

        String csvKey = attributeMap.getOrDefault(searchBy, "");  // Get corresponding CSV column
        if (csvKey.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Invalid search attribute.");
            return;
        }
        
        FileOperations fileOps = new FileOperations();
        String className = "Item";
        List<Map<String, String>> items = fileOps.ReadFile(className + ".csv");
        boolean found = false;
        DefaultTableModel model = (DefaultTableModel) tblItemEdit.getModel();
        model.setRowCount(0); // Clear table first

        for (Map<String, String> row : items) {
            if (keyword.equalsIgnoreCase(row.get(csvKey))) {
                model.addRow(new Object[]{
                    row.get("Item Code"),
                    row.get("Item Name"),
                    row.get("Supplier ID"),
                    row.get("Stock Level"),
                    row.get("Unit Price"),
                    row.get("Reorder Level")
                });
                found = true;
                break;
            }
        }

        if (!found) {
            JOptionPane.showMessageDialog(this, searchBy + " not found.");
        } else {
            btnUpdate.setEnabled(true);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblItemEdit.getModel();
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No item data to update.");
            return;
        }
    
        try {
            // Get selected search attribute (e.g., "Item ID", "Supplier ID", etc.)
            String searchBy = comboSearchBy.getSelectedItem().toString().trim();
            String keyword = txtSearchKeyword.getText().trim();
        
            if (keyword.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter a search keyword.");
                return;
            }
        
            // Map from combo box attribute label to CSV column keys
            Map<String, String> attributeMap = new HashMap<>();
            attributeMap.put("Item ID", "Item Code");
            attributeMap.put("Item Name", "Item Name");
            attributeMap.put("Supplier ID", "Supplier ID");
            attributeMap.put("Supplier Name", "Supplier Name");

            String csvKey = attributeMap.getOrDefault(searchBy, "");
            if (csvKey.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Invalid search attribute.");
                return;
            }
        
            // Extract updated values from table (columns: 0=Item Code, 1=Item Name, 2=Supplier ID, 3=Stock Level, 4=Unit Price, 5=Reorder Level)
            String newItemCode = model.getValueAt(0, 0).toString();
            String newItemName = model.getValueAt(0, 1).toString();
            String newSupplierID = model.getValueAt(0, 2).toString();
            int newStockLevel = Integer.parseInt(model.getValueAt(0, 3).toString());
            double newUnitPrice = Double.parseDouble(model.getValueAt(0, 4).toString());
            int newReorderLevel = Integer.parseInt(model.getValueAt(0, 5).toString());
        
            FileOperations fileOps = new FileOperations();
            List<Map<String, String>> items = fileOps.ReadFile("Item.csv");
        
            boolean updated = false;
        
            // Update the matching record based on the selected search attribute and keyword
            for (Map<String, String> row : items) {
                if (row.get(csvKey).equalsIgnoreCase(keyword)) {
                    row.put("Item Code", newItemCode);
                    row.put("Item Name", newItemName);
                    row.put("Supplier ID", newSupplierID);
                    row.put("Stock Level", String.valueOf(newStockLevel));
                    row.put("Unit Price", String.valueOf(newUnitPrice));
                    row.put("Reorder Level", String.valueOf(newReorderLevel));
                    updated = true;
                    break;
                }
            }
        
            if (updated) {
                // Clear original file
                new PrintWriter("Item.csv").close();

                // Rewrite updated list back to file
                for (Map<String, String> row : items) {
                    Item item = new Item(
                        row.get("Item Code"),
                        row.get("Item Name"),
                        row.get("Supplier ID"),
                        Integer.parseInt(row.get("Stock Level")),
                        Double.parseDouble(row.get("Unit Price")),
                        Integer.parseInt(row.get("Reorder Level"))
                    );
                    fileOps.WriteFile(item);
                }
                JOptionPane.showMessageDialog(this, "Item updated successfully.");
            } else {
                JOptionPane.showMessageDialog(this, searchBy + " '" + keyword + "' not found. Cannot update.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid numeric values. Please enter valid numbers.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error updating item: " + e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditItemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditItemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditItemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditItemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditItemGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> comboSearchBy;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblItemEdit;
    private javax.swing.JTextField txtSearchKeyword;
    // End of variables declaration//GEN-END:variables
}
