package com.group.apomsproject;

import java.lang.reflect.Method;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class PMGUI extends javax.swing.JFrame {
    private final PurchaseManager manager;
    private TableRowSorter<DefaultTableModel> tableSorter;
    private PurchaseRequisition currentPR = null;
    private String targetSPID;
    
    private void PRMODEditable(boolean toggle)
    {
        txtPRIDMod.setEditable(!toggle);
        btnApprove.setEnabled(toggle);
        btnReject.setEnabled(toggle);        
    }
    /**
     * Creates new form PMGUI
     * @param manager
     */
    public PMGUI(PurchaseManager manager) {
        this.manager = manager;
        initComponents();
        PRMODEditable(false);
        txtPRStatusMod.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        tab = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        POTab = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        txtPRSearchField = new javax.swing.JTextField();
        btnSearchPR = new javax.swing.JButton();
        btnShowPR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPR = new javax.swing.JTable();
        jLabel42 = new javax.swing.JLabel();
        btnPRUpdateClear = new javax.swing.JButton();
        txtPRIDMod = new javax.swing.JTextField();
        btnPRUpdateSearchID = new javax.swing.JButton();
        txtPRStatusMod = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        btnApprove = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblISM = new javax.swing.JTable();
        jLabel43 = new javax.swing.JLabel();
        lblItemID = new javax.swing.JLabel();
        txtPOSp = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        btnChooseSp = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txtPODate = new javax.swing.JTextField();
        txtPOID = new javax.swing.JTextField();
        btnAddPR = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        txtPOSearchField = new javax.swing.JTextField();
        btnSearchPO = new javax.swing.JButton();
        btnShowPO = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPO = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnShowItemBR = new javax.swing.JButton();
        btnShowItem = new javax.swing.JButton();
        txtItemSearchField = new javax.swing.JTextField();
        btnSearchItem = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        txtSpSearchField = new javax.swing.JTextField();
        btnSearchSp = new javax.swing.JButton();
        btnShowSp = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblSp = new javax.swing.JTable();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("PO Entry");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblName.setText("PMName");

        btnLogout.setBackground(new java.awt.Color(0, 0, 0));
        btnLogout.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel2.setText("purchase");

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel1.setText("Manager");

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("View Items");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("View Suppliers");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblName)
                .addContainerGap())
        );

        txtPRSearchField.setToolTipText("Enter keyword to search...");
        txtPRSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPRSearchFieldActionPerformed(evt);
            }
        });

        btnSearchPR.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btnSearchPR.setText("Search");
        btnSearchPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchPRActionPerformed(evt);
            }
        });

        btnShowPR.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btnShowPR.setText("Load Purchase Requisition");
        btnShowPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowPRActionPerformed(evt);
            }
        });

        tblPR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPR);

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel42.setText("PR ID");

        btnPRUpdateClear.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btnPRUpdateClear.setText("Clear");
        btnPRUpdateClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPRUpdateClearActionPerformed(evt);
            }
        });

        txtPRIDMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPRIDModActionPerformed(evt);
            }
        });

        btnPRUpdateSearchID.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btnPRUpdateSearchID.setText("Search");
        btnPRUpdateSearchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPRUpdateSearchIDActionPerformed(evt);
            }
        });

        txtPRStatusMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPRStatusModActionPerformed(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel45.setText("Status");

        btnApprove.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btnApprove.setText("Approve PR");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        btnReject.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btnReject.setText("Reject PR");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnShowPR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPRSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchPR))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel45)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPRStatusMod))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel42)
                                .addGap(18, 18, 18)
                                .addComponent(txtPRIDMod, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(btnPRUpdateSearchID)
                                .addGap(18, 18, 18)
                                .addComponent(btnPRUpdateClear)))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnApprove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPRSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearchPR))
                    .addComponent(btnShowPR))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPRUpdateSearchID)
                        .addComponent(btnPRUpdateClear)
                        .addComponent(btnApprove))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel42)
                        .addComponent(txtPRIDMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReject)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel45)
                        .addComponent(txtPRStatusMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        POTab.addTab("View PR", jPanel5);

        tblISM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblISM);

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel43.setText("Suppliers for");

        lblItemID.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblItemID.setText("Item ID");

        txtPOSp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPOSpActionPerformed(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel46.setText("Enter Desired Supplier ID");

        btnChooseSp.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btnChooseSp.setText("Choose");
        btnChooseSp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseSpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel43)
                        .addGap(18, 18, 18)
                        .addComponent(lblItemID))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnChooseSp)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel46)
                            .addGap(18, 18, 18)
                            .addComponent(txtPOSp, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(lblItemID))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(txtPOSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnChooseSp)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        POTab.addTab("Choose Supplier", jPanel6);

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel41.setText("Date Created");

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel44.setText("PO ID");

        txtPODate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPODateActionPerformed(evt);
            }
        });

        txtPOID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPOIDActionPerformed(evt);
            }
        });

        btnAddPR.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        btnAddPR.setText("Add");
        btnAddPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddPR)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addGap(18, 18, 18)
                        .addComponent(txtPODate, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel44)
                        .addGap(18, 18, 18)
                        .addComponent(txtPOID, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(txtPOID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(txtPODate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btnAddPR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        POTab.addTab("Generate PO", jPanel7);

        txtPOSearchField.setToolTipText("Enter keyword to search...");
        txtPOSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPOSearchFieldActionPerformed(evt);
            }
        });

        btnSearchPO.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btnSearchPO.setText("Search");
        btnSearchPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchPOActionPerformed(evt);
            }
        });

        btnShowPO.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btnShowPO.setText("Load Purchase Order");
        btnShowPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowPOActionPerformed(evt);
            }
        });

        tblPO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblPO);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(btnShowPO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPOSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchPO)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPOSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearchPO))
                    .addComponent(btnShowPO))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        POTab.addTab("View PO", jPanel8);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(POTab)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(POTab)
        );

        tab.addTab("tab1", jPanel2);

        btnShowItemBR.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btnShowItemBR.setText("Low Stock Filter");
        btnShowItemBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowItemBRActionPerformed(evt);
            }
        });

        btnShowItem.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btnShowItem.setText("Load Items");
        btnShowItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowItemActionPerformed(evt);
            }
        });

        txtItemSearchField.setToolTipText("Enter keyword to search...");
        txtItemSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemSearchFieldActionPerformed(evt);
            }
        });

        btnSearchItem.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btnSearchItem.setText("Search");
        btnSearchItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchItemActionPerformed(evt);
            }
        });

        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblItem);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnShowItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnShowItemBR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtItemSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchItem)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtItemSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearchItem))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnShowItem)
                        .addComponent(btnShowItemBR)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        tab.addTab("tab2", jPanel3);

        txtSpSearchField.setToolTipText("Enter keyword to search...");
        txtSpSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpSearchFieldActionPerformed(evt);
            }
        });

        btnSearchSp.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btnSearchSp.setText("Search");
        btnSearchSp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchSpActionPerformed(evt);
            }
        });

        btnShowSp.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btnShowSp.setText("Load Suppliers");
        btnShowSp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowSpActionPerformed(evt);
            }
        });

        tblSp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tblSp);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnShowSp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSpSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchSp)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSpSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearchSp))
                    .addComponent(btnShowSp))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        tab.addTab("tab3", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tab.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        MainGUI gui = new MainGUI();
        gui.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        tab.setSelectedIndex(1);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        tab.setSelectedIndex(2);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtPRSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPRSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPRSearchFieldActionPerformed

    private void btnSearchPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchPRActionPerformed
        String keyword = txtPRSearchField.getText().trim();

        if(keyword.isEmpty())
        {
            tableSorter.setRowFilter(null);
        }
        else
        {
            try
            {
                RowFilter<DefaultTableModel, Object> filter = RowFilter.regexFilter("(?i)" + keyword);
                tableSorter.setRowFilter(filter);

                if(tblPR.getRowCount() == 0)
                {
                    JOptionPane.showMessageDialog(this, "No matches found for: " + keyword);
                }
            }
            catch(Exception e)
            {
                tableSorter.setRowFilter(null);
                JOptionPane.showMessageDialog(this, "Invalid search keyword: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnSearchPRActionPerformed

    private void btnShowPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowPRActionPerformed
        DefaultTableModel model = manager.viewTable("PurchaseRequisition");
        tblPR.setModel(model);
        tableSorter = new TableRowSorter((DefaultTableModel) tblPR.getModel());
        tblPR.setRowSorter(tableSorter);
    }//GEN-LAST:event_btnShowPRActionPerformed

    private void btnPRUpdateClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPRUpdateClearActionPerformed
        txtPRIDMod.setText("");
        txtPRStatusMod.setText("");
        PRMODEditable(false);
        currentPR = null;
    }//GEN-LAST:event_btnPRUpdateClearActionPerformed

    private void txtPRIDModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPRIDModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPRIDModActionPerformed

    private void btnPRUpdateSearchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPRUpdateSearchIDActionPerformed
        String id = txtPRIDMod.getText().trim();
        boolean found = false;

        List<PurchaseRequisition> prs = manager.recreatePRs();
        for(PurchaseRequisition pr : prs)
        {
            if(id.equals(pr.getPRID()))
            {
                currentPR = pr;
                found = true;
                break;
            }
        }

        if(!found)
        {
            JOptionPane.showMessageDialog(this, "Purchase Requisition " + id + " not found");
        }
        else
        {
            txtPRStatusMod.setText(currentPR.getStatus());
            PRMODEditable(true);
        }
    }//GEN-LAST:event_btnPRUpdateSearchIDActionPerformed

    private void txtPRStatusModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPRStatusModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPRStatusModActionPerformed

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        if(txtPRStatusMod.getText().trim().equals("pending"))
        {
            POTab.setSelectedIndex(1);
            lblItemID.setText(currentPR.getItemID());
            DefaultTableModel model = manager.viewTable("ItemSupplierMap");
            tblISM.setModel(model);
            tableSorter = new TableRowSorter((DefaultTableModel) tblISM.getModel());
            tblISM.setRowSorter(tableSorter);
            RowFilter<DefaultTableModel, Object> filter = RowFilter.regexFilter("(?i)" + currentPR.getItemID());
            tableSorter.setRowFilter(filter);
        }
        else if(txtPRStatusMod.getText().trim().equals("approved"))
        {
            JOptionPane.showMessageDialog(this, "PR is already approved");
        }
        else
        {
            JOptionPane.showMessageDialog(this, "PR is previously rejected");
        }
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        String id = txtPRIDMod.getText().trim();
        String status = txtPRStatusMod.getText().trim();
        
        if(!status.equals("pending"))
        {
            JOptionPane.showMessageDialog(this, "PR is not in pending state");
        }
        else
        {
            currentPR.setStatus("rejected");
            manager.updateObject(currentPR, currentPR.getPRID());
            txtPRIDMod.setText("");
            txtPRStatusMod.setText("");
            PRMODEditable(false);
            currentPR = null;
            JOptionPane.showMessageDialog(this, "PurchaseRequisition" + id + " rejected" );
        }
    }//GEN-LAST:event_btnRejectActionPerformed

    private void txtPOSpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPOSpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPOSpActionPerformed

    private void btnChooseSpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseSpActionPerformed
        targetSPID = txtPOSp.getText().trim();
        POTab.setSelectedIndex(2);
    }//GEN-LAST:event_btnChooseSpActionPerformed

    private void txtPODateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPODateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPODateActionPerformed

    private void txtPOIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPOIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPOIDActionPerformed

    private void btnAddPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPRActionPerformed
        manager.addPO
        (
                txtPOID.getText().trim(),
                currentPR.getPRID(),
                currentPR.getItemID(),
                currentPR.getRequiredQuantity(),
                targetSPID,
                txtPODate.getText().trim(),
                manager.getPMID()
        );
        
        currentPR.setStatus("approved");
        manager.updateObject(currentPR, currentPR.getPRID());
        currentPR = null;
        targetSPID = null;
        txtPOID.setText("");
        txtPODate.setText("");
        txtPOSp.setText("");
        txtPRIDMod.setText("");
        txtPRStatusMod.setText("");
        PRMODEditable(false);
    }//GEN-LAST:event_btnAddPRActionPerformed

    private void txtPOSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPOSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPOSearchFieldActionPerformed

    private void btnSearchPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchPOActionPerformed
        String keyword = txtPOSearchField.getText().trim();

        if(keyword.isEmpty())
        {
            tableSorter.setRowFilter(null);
        }
        else
        {
            try
            {
                RowFilter<DefaultTableModel, Object> filter = RowFilter.regexFilter("(?i)" + keyword);
                tableSorter.setRowFilter(filter);

                if(tblPO.getRowCount() == 0)
                {
                    JOptionPane.showMessageDialog(this, "No matches found for: " + keyword);
                }
            }
            catch(Exception e)
            {
                tableSorter.setRowFilter(null);
                JOptionPane.showMessageDialog(this, "Invalid search keyword: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnSearchPOActionPerformed

    private void btnShowPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowPOActionPerformed
        DefaultTableModel model = manager.viewTable("PurchaseOrder");
        tblPO.setModel(model);
        tableSorter = new TableRowSorter((DefaultTableModel) tblPO.getModel());
        tblPO.setRowSorter(tableSorter);
    }//GEN-LAST:event_btnShowPOActionPerformed

    private void btnShowItemBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowItemBRActionPerformed
        try
        {
            int quantityColumnIndex = 3;
            int rolColumnIndex = 4;

            RowFilter<DefaultTableModel, Object> filter = new RowFilter<DefaultTableModel, Object>()
            {
                @Override
                public boolean include(Entry<? extends DefaultTableModel, ? extends Object> entry)
                {
                    Object quantityObj = entry.getValue(quantityColumnIndex);
                    Object rolObj = entry.getValue(rolColumnIndex);

                    if(quantityObj == null || rolObj == null)
                    {
                        return false;
                    }

                    try
                    {
                        int quantity = Integer.parseInt(quantityObj.toString());
                        int rol = Integer.parseInt(rolObj.toString());
                        return quantity < rol;
                    }
                    catch(NumberFormatException e)
                    {
                        return false;
                    }
                }
            };
            tableSorter.setRowFilter(filter);

            if(tblItem.getRowCount() == 0)
            {
                JOptionPane.showMessageDialog(this, "No items with low stock");
            }
        }
        catch(Exception e)
        {
            tableSorter.setRowFilter(null);
            JOptionPane.showMessageDialog(this, "Error filtering low stock: " + e.getMessage());
        }
    }//GEN-LAST:event_btnShowItemBRActionPerformed

    private void btnShowItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowItemActionPerformed
        DefaultTableModel model = manager.viewTable("Item");
        tblItem.setModel(model);
        tableSorter = new TableRowSorter((DefaultTableModel) tblItem.getModel());
        tblItem.setRowSorter(tableSorter);
    }//GEN-LAST:event_btnShowItemActionPerformed

    private void txtItemSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemSearchFieldActionPerformed

    private void btnSearchItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchItemActionPerformed
        String keyword = txtItemSearchField.getText().trim();

        if(keyword.isEmpty())
        {
            tableSorter.setRowFilter(null);
        }
        else
        {
            try
            {
                RowFilter<DefaultTableModel, Object> filter = RowFilter.regexFilter("(?i)" + keyword);
                tableSorter.setRowFilter(filter);

                if(tblItem.getRowCount() == 0)
                {
                    JOptionPane.showMessageDialog(this, "No matches found for: " + keyword);
                }
            }
            catch(Exception e)
            {
                tableSorter.setRowFilter(null);
                JOptionPane.showMessageDialog(this, "Invalid search keyword: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnSearchItemActionPerformed

    private void txtSpSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpSearchFieldActionPerformed

    private void btnSearchSpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchSpActionPerformed
        String keyword = txtSpSearchField.getText().trim();

        if(keyword.isEmpty())
        {
            tableSorter.setRowFilter(null);
        }
        else
        {
            try
            {
                RowFilter<DefaultTableModel, Object> filter = RowFilter.regexFilter("(?i)" + keyword);
                tableSorter.setRowFilter(filter);

                if(tblSp.getRowCount() == 0)
                {
                    JOptionPane.showMessageDialog(this, "No matches found for: " + keyword);
                }
            }
            catch(Exception e)
            {
                tableSorter.setRowFilter(null);
                JOptionPane.showMessageDialog(this, "Invalid search keyword: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnSearchSpActionPerformed

    private void btnShowSpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowSpActionPerformed
        DefaultTableModel model = manager.viewTable("Supplier");
        tblSp.setModel(model);
        tableSorter = new TableRowSorter((DefaultTableModel) tblSp.getModel());
        tblSp.setRowSorter(tableSorter);
    }//GEN-LAST:event_btnShowSpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PMGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PMGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PMGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PMGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PMGUI(new PurchaseManager("1", "1", "1", "1", "1")).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane POTab;
    private javax.swing.JButton btnAddPR;
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnChooseSp;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPRUpdateClear;
    private javax.swing.JButton btnPRUpdateSearchID;
    private javax.swing.JButton btnReject;
    private javax.swing.JButton btnSearchItem;
    private javax.swing.JButton btnSearchPO;
    private javax.swing.JButton btnSearchPR;
    private javax.swing.JButton btnSearchSp;
    private javax.swing.JButton btnShowItem;
    private javax.swing.JButton btnShowItemBR;
    private javax.swing.JButton btnShowPO;
    private javax.swing.JButton btnShowPR;
    private javax.swing.JButton btnShowSp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblItemID;
    private javax.swing.JLabel lblName;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTable tblISM;
    private javax.swing.JTable tblItem;
    private javax.swing.JTable tblPO;
    private javax.swing.JTable tblPR;
    private javax.swing.JTable tblSp;
    private javax.swing.JTextField txtItemSearchField;
    private javax.swing.JTextField txtPODate;
    private javax.swing.JTextField txtPOID;
    private javax.swing.JTextField txtPOSearchField;
    private javax.swing.JTextField txtPOSp;
    private javax.swing.JTextField txtPRIDMod;
    private javax.swing.JTextField txtPRSearchField;
    private javax.swing.JTextField txtPRStatusMod;
    private javax.swing.JTextField txtSpSearchField;
    // End of variables declaration//GEN-END:variables
}
